### ISSUE TITLE
Termux issue

### ISSUE THREAD

**Issue by RexAckermann** [AineeJames/ChatGPTerminator#11]
Crashed if dalle is used.Image and link is okay.But then it crashes.Copy to clipboard might be the issue.

`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/gpterm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/gpterminator/__main__.py", line 6, in main
    app.run()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/gpterminator/GPTerminator.py", line 484, in run
    usr_input = self.queryUser()
                ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/gpterminator/GPTerminator.py", line 328, in queryUser
    self.useDalle()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/gpterminator/GPTerminator.py", line 251, in useDalle
    pyperclip.copy(image_url)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
           ^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error
_p9k_worker_invoke:print:5: write error: broken pipe
_p9k_worker_invoke:print:5: write error: broken pipe
_p9k_worker_invoke:print:5: write error: broken pipe`

**Comment by AineeJames** [comment]
I would recommend visiting this [link](https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error). Clipboards are different on all systems so that's probably the issue.

**Comment by AineeJames** [comment]
Closing due to inactivity. See the following issue for fix: #13
