### ISSUE TITLE
Won't work with containerization

### ISSUE THREAD

**Issue by webgtx** [AineeJames/ChatGPTerminator#6]
Well, I'm trying to build container image. And I stuck with this **python error**, this stderr appears when I'm running your script in container.

### STDERR
```bash
?main ~/Desktop/devroom/ChatGPTerminator> podman run -it --name gpterm gpterm  
Traceback (most recent call last):
  File "/usr/local/bin/gpterm", line 5, in <module>
    from gpterminator.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/gpterminator/__main__.py", line 1, in <module>
    from . import GPTerminator
  File "/usr/local/lib/python3.9/site-packages/gpterminator/GPTerminator.py", line 168
    match msg["role"]:
          ^
SyntaxError: invalid syntax
exit 1
```

### Dockerfile
```Dockerfile
FROM python:3.9-alpine
WORKDIR /root
COPY . .
RUN mkdir -p /root/.config/gpterminator
RUN pip install . 
ARG APIKEY
ENV OPENAI_API_KEY=$APIKEY
CMD ["gpterm"]
```

**Comment by AineeJames** [comment]
Match case was introduced in Python 3.10, try updating and trying again!

**Comment by AineeJames** [comment]
I plan to switch to if else statements soon to make it more comparable with older versions...

**Comment by webgtx** [comment]
Alright, I'll check soon

**Comment by webgtx** [comment]
Everything is fine
